spring.datasource.url=jdbc:postgresql://ep-little-bonus-am8t2ufa-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NhM9puL4ZsPR
spring.datasource.driver-class-name=org.postgresql.Driver


#creates table if doesnt exist
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

